export interface EquipmentRentalInfo {
  bootsRental: boolean;      // Krampon kiralama var mı?
  bootsFee?: number;         // Krampon ücreti (TL)
  glovesRental: boolean;     // Kaleci eldiveni kiralama var mı?
  glovesFee?: number;        // Eldiven ücreti (TL)
  vestsProvided?: boolean;   // Yelek veriliyor mu?
  showerAvailable?: boolean; // Sıcak duş / soyunma odası
  parkingAvailable?: boolean;// Otopark imkanı
}

export interface SubFieldInfo {
  id: string;
  name: string;
  surface: 'Suni Çim' | 'Hibrit Çim' | 'Kapalı Saha';
  startSlot?: string;        // e.g. "09:00"
  lastSlot?: string;         // e.g. "21:00-22:00"
  slotType?: 'full' | 'half';// full = tam saat, half = yarım saat
}

export interface PitchDatabaseItem {
  id: string;
  city: string;
  district: string;
  name: string;
  rating: number;
  isPopular?: boolean;
  hourlyFee?: number;        // Tek maç saatlik ücreti (TL)
  subscriberFee?: number;    // Abone saatlik ücreti (TL)
  openingTime?: string;      // örn: "09:00"
  closingTime?: string;      // örn: "22:00"
  optimalModes?: string[];   // İdeal oynanan formatlar: örn ['7v7'] (yeşil / uyarı yok)
  tightModes?: string[];     // Sıkışık da olsa oynanabilen formatlar: örn ['8v8'] (sarı uyarı)
  equipmentRental?: EquipmentRentalInfo;
  phone?: string;
  address?: string;
  subFields: SubFieldInfo[];
}

export const PITCH_DATABASE: PitchDatabaseItem[] = [

  // ─── ANKARA ────────────────────────────────────────────────────────────────

  // Çankaya
  {
    id: 'ank-odtu',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'ODTÜ Halı Saha Tesisleri',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 2800,
    subscriberFee: 2500,
    openingTime: '09:00',
    closingTime: '00:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 210 20 00',
    address: 'Üniversiteler Mah., Dumlupınar Blv. No:1, ODTÜ Kampüsü, Çankaya',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'odtu-1', name: 'Halı Saha 1 (Açık)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '23:00-00:00', slotType: 'full' },
      { id: 'odtu-2', name: 'Halı Saha 2 (Açık)', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '22:30-23:30', slotType: 'half' },
      { id: 'odtu-3', name: 'Halı Saha 3 (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '23:00-00:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-hacettepe-beytepe',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Hacettepe Üniversitesi Beytepe Spor Tesisleri',
    rating: 4.7,
    isPopular: true,
    hourlyFee: 2600,
    subscriberFee: 2300,
    openingTime: '08:30',
    closingTime: '23:30',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 297 60 00',
    address: 'Beytepe Kampüsü, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'hac-1', name: '1. Saha (Açık)', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:30-23:30', slotType: 'half' },
      { id: 'hac-2', name: '2. Saha (Açık)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: 'hac-3', name: 'Kapalı Salon Sahası', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-baskent-dikmen',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Başkent Kapalı Halı Saha Tesisleri',
    rating: 4.9,
    isPopular: true,
    hourlyFee: 3200,
    subscriberFee: 2800,
    openingTime: '09:00',
    closingTime: '02:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 480 50 50',
    address: 'Dikmen Cad. No:242, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 80,
      glovesRental: true,
      glovesFee: 50,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'baskent-1', name: 'Saha A (FIFA Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'baskent-2', name: 'Saha B (Isıtmalı Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-cinar-ovecler',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Çınar Halı Saha Kompleksi',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 3000,
    subscriberFee: 2700,
    openingTime: '09:00',
    closingTime: '01:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 472 15 15',
    address: 'Öveçler Vadisi, Çetin Emeç Blv., Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'cinar-1', name: '1. Saha (Vadi)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'cinar-2', name: '2. Saha (Arena)', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-anittepe',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Anıttepe Kapalı Spor Tesisleri (AKS)',
    rating: 4.7,
    isPopular: true,
    hourlyFee: 2900,
    subscriberFee: 2600,
    openingTime: '08:00',
    closingTime: '23:30',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 231 10 20',
    address: 'Gençlik Cad. No:14, Anıttepe, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'anit-1', name: 'Ana Kapalı Saha', surface: 'Kapalı Saha', startSlot: '08:00', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: 'anit-2', name: 'Açık Halı Saha', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:30-23:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-futbol-arena-sancak',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Futbol Arena Çankaya',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 3100,
    subscriberFee: 2800,
    openingTime: '09:00',
    closingTime: '01:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 440 88 90',
    address: 'Sancak Mah., Simon Bolivar Cad., Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 75,
      glovesRental: true,
      glovesFee: 45,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'fa-1', name: 'Arena 1', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'fa-2', name: 'Arena 2 (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-bilkent',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Bilkent Üniversitesi Halı Saha Tesisleri',
    rating: 4.7,
    isPopular: true,
    hourlyFee: 2800,
    subscriberFee: 2500,
    openingTime: '09:00',
    closingTime: '23:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 290 19 91',
    address: 'Bilkent Merkez Kampüs, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'bil-1', name: 'Ana Halı Saha (Açık)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: 'bil-2', name: 'Kapalı Salon Sahası', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '21:30-22:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-star-dust-balgat',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Star Dust Halı Saha Tesisleri',
    rating: 4.6,
    hourlyFee: 2900,
    subscriberFee: 2600,
    openingTime: '10:00',
    closingTime: '02:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 284 30 40',
    address: 'Ziyabey Cad. 1421. Sok., Balgat, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 65,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'sd-1', name: 'Saha 1', surface: 'Suni Çim', startSlot: '10:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'sd-2', name: 'Saha 2', surface: 'Suni Çim', startSlot: '10:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-ada-kirkkonaklar',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Ada Halı Saha Tesisleri',
    rating: 4.5,
    hourlyFee: 2700,
    subscriberFee: 2400,
    openingTime: '09:00',
    closingTime: '01:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 495 20 30',
    address: 'Şemsettin Günaltay Cad., Kırkkonaklar, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'ada-1', name: '1. Saha (Açık)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'ada-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-ahlatlibel-kompleks',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Ahlatlıbel Atatürk Parkı Halı Sahaları',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 2900,
    subscriberFee: 2600,
    openingTime: '08:30',
    closingTime: '23:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 490 00 11',
    address: 'İncek Yolu, Ahlatlıbel Atatürk Parkı İçi, Çankaya, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'ahlat-1', name: '1. Saha (Orman Tarafı)', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:30-23:30', slotType: 'half' },
      { id: 'ahlat-2', name: '2. Saha (Merkez)', surface: 'Hibrit Çim', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },

  // Yenimahalle & Batıkent
  {
    id: 'ank-mobil-batikent',
    city: 'Ankara',
    district: 'Batıkent',
    name: 'Mobil Halısaha Batıkent (FIFA Zemin)',
    rating: 4.9,
    isPopular: true,
    hourlyFee: 3000,
    subscriberFee: 2700,
    openingTime: '09:00',
    closingTime: '02:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 250 80 90',
    address: 'İnönü Mah., Batıkent Blv. No:45, Batıkent, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 75,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'mb-1', name: 'Saha 1 (FIFA Onaylı & Kameralı)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'mb-2', name: 'Saha 2 (Açık)', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
      { id: 'mb-3', name: 'Saha 3 (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-batikent-arena',
    city: 'Ankara',
    district: 'Batıkent',
    name: 'Batıkent Arena Spor Tesisleri',
    rating: 4.7,
    isPopular: true,
    hourlyFee: 2800,
    subscriberFee: 2500,
    openingTime: '09:00',
    closingTime: '01:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 251 40 40',
    address: 'İlkyerleşim Mah., 1904. Cad., Batıkent, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 65,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'ba-1', name: 'Arena Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'ba-2', name: 'Açık Saha', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-batikent-park',
    city: 'Ankara',
    district: 'Batıkent',
    name: 'Batıkent Park Halı Saha',
    rating: 4.6,
    hourlyFee: 2600,
    subscriberFee: 2300,
    openingTime: '09:00',
    closingTime: '01:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 255 12 12',
    address: 'Batıkent Spor ve Dinlenme Parkı, Cuma Pazarı Yanı, Batıkent',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'bp-1', name: '1. Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'bp-2', name: '2. Saha', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-aybesk-batikent',
    city: 'Ankara',
    district: 'Batıkent',
    name: 'Aybesk Halı Saha Tesisleri',
    rating: 4.5,
    hourlyFee: 2700,
    subscriberFee: 2400,
    openingTime: '09:00',
    closingTime: '01:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 256 70 70',
    address: 'Uğur Mumcu Mah., 1600. Cad., Batıkent, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'ayb-1', name: 'Açık Suni Çim Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'ayb-2', name: 'Kapalı Saha', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-hasan-dogan-yenimahalle',
    city: 'Ankara',
    district: 'Yenimahalle',
    name: 'Hasan Doğan Spor Kompleksi Halı Sahası',
    rating: 4.6,
    hourlyFee: 2500,
    subscriberFee: 2200,
    openingTime: '08:30',
    closingTime: '23:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 344 55 66',
    address: 'Gayret Mah., İvedik Cad., Yenimahalle, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'hd-1', name: '1. Saha (Belediye)', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:30-23:30', slotType: 'half' },
      { id: 'hd-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-camlica-yenimahalle',
    city: 'Ankara',
    district: 'Yenimahalle',
    name: 'Çamlıca Halı Saha Tesisleri',
    rating: 4.5,
    hourlyFee: 2600,
    subscriberFee: 2300,
    openingTime: '09:00',
    closingTime: '01:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 397 22 33',
    address: 'Çamlıca Mah., Anadolu Blv., Yenimahalle, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'cam-1', name: '1. Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'cam-2', name: '2. Saha', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },

  // Etimesgut & Eryaman
  {
    id: 'ank-goksu-eryaman',
    city: 'Ankara',
    district: 'Eryaman',
    name: 'Göksu Park Halı Saha Tesisleri',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 2900,
    subscriberFee: 2600,
    openingTime: '09:00',
    closingTime: '01:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 280 40 50',
    address: 'Göksu Mah., Göksu Parkı İçi, Eryaman, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'gok-1', name: '1. Saha (Göl Manzaralı)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'gok-2', name: '2. Saha (Açık)', surface: 'Hibrit Çim', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-eryaman-elit',
    city: 'Ankara',
    district: 'Eryaman',
    name: 'Eryaman Elit Halı Saha Kompleksi',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 2950,
    subscriberFee: 2650,
    openingTime: '08:30',
    closingTime: '02:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 282 00 22',
    address: 'Şehit Osman Avcı Mah., Malazgirt 1071 Cad., Eryaman',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 75,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'ery-1', name: '1. Saha (Suni Çim)', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '00:30-01:30', slotType: 'half' },
      { id: 'ery-2', name: '2. Saha (Hibrit Zemin)', surface: 'Hibrit Çim', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'ery-3', name: 'Kapalı Arena Saha', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-emiryaman',
    city: 'Ankara',
    district: 'Eryaman',
    name: 'Emiryaman Spor Tesisleri',
    rating: 4.6,
    hourlyFee: 2700,
    subscriberFee: 2400,
    openingTime: '09:00',
    closingTime: '01:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 283 55 44',
    address: 'Eryaman Mah., 326. Sok., Eryaman, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 65,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'emr-1', name: 'Açık Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'emr-2', name: 'Kapalı Saha', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-baglica-zirve',
    city: 'Ankara',
    district: 'Etimesgut',
    name: 'Bağlıca Zirve Halı Saha Tesisleri',
    rating: 4.7,
    isPopular: true,
    hourlyFee: 2850,
    subscriberFee: 2550,
    openingTime: '09:00',
    closingTime: '02:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 234 11 22',
    address: 'Bağlıca Mah., Bağlıca Blv. No:110, Etimesgut, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'bgz-1', name: '1. Saha (Açık)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'bgz-2', name: '2. Saha (Isıtmalı Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-etimesgut-devlet-bahceli',
    city: 'Ankara',
    district: 'Etimesgut',
    name: 'Devlet Bahçeli Spor Yerleşkesi Sahaları',
    rating: 4.6,
    hourlyFee: 2400,
    subscriberFee: 2100,
    openingTime: '08:00',
    closingTime: '23:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 245 00 10',
    address: 'Bağlıca Mah., Devlet Bahçeli Spor Yerleşkesi, Etimesgut',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 50,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'dbh-1', name: 'Ana Halı Saha', surface: 'Suni Çim', startSlot: '08:00', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: 'dbh-2', name: '2. Saha', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '21:30-22:30', slotType: 'half' },
      { id: 'dbh-3', name: 'Kapalı Saha', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },

  // Keçiören
  {
    id: 'ank-altin11-kecioren',
    city: 'Ankara',
    district: 'Keçiören',
    name: 'ALTIN 11 - Ankara Atletik Halı Saha',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 2900,
    subscriberFee: 2600,
    openingTime: '09:00',
    closingTime: '02:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 325 11 11',
    address: 'Ayvalı Cad. No:82, Aşağı Eğlence, Keçiören, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'alt-1', name: '1. Saha (Altın Arena)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'alt-2', name: '2. Saha (Açık)', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
      { id: 'alt-3', name: '3. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-kucukev-etlik',
    city: 'Ankara',
    district: 'Keçiören',
    name: 'Küçük Ev Halı Saha (Etlik)',
    rating: 4.5,
    hourlyFee: 2700,
    subscriberFee: 2400,
    openingTime: '09:00',
    closingTime: '01:30',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 322 30 30',
    address: 'Ayvalı Mah., Halil Sezai Erkut Cad., Etlik, Keçiören',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'ke-1', name: '1. Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'ke-2', name: '2. Saha', surface: 'Suni Çim', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-kecioren-aktepe',
    city: 'Ankara',
    district: 'Keçiören',
    name: 'Keçiören Aktepe Stadyumu Sahaları',
    rating: 4.4,
    hourlyFee: 2400,
    subscriberFee: 2100,
    openingTime: '08:30',
    closingTime: '23:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 359 00 22',
    address: 'Aktepe Mah., 969. Cad., Keçiören, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 50,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'akt-1', name: 'Ana Saha', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: 'akt-2', name: 'Yan Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-kuscagiz-kecioren',
    city: 'Ankara',
    district: 'Keçiören',
    name: 'Kuşcağız Aile Yaşam Merkezi Halı Sahası',
    rating: 4.5,
    hourlyFee: 2200,
    subscriberFee: 1950,
    openingTime: '08:30',
    closingTime: '22:30',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 380 10 10',
    address: 'Sanatoryum Cad. No:273, Kuşcağız, Keçiören, Ankara',
    equipmentRental: {
      bootsRental: false,
      glovesRental: true,
      glovesFee: 25,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'kusc-1', name: '1. Saha (Açık)', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '21:30-22:30', slotType: 'half' },
      { id: 'kusc-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '21:00-22:00', slotType: 'full' },
    ],
  },

  // Gölbaşı
  {
    id: 'ank-golbasi-sen',
    city: 'Ankara',
    district: 'Gölbaşı',
    name: 'Gölbaşı Şen Halı Saha Tesisleri',
    rating: 4.8,
    isPopular: true,
    hourlyFee: 2900,
    subscriberFee: 2600,
    openingTime: '09:00',
    closingTime: '02:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 484 20 20',
    address: 'Karşıyaka Mah., Haymana Yolu (Mogan Parkı Karşısı), Gölbaşı, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 70,
      glovesRental: true,
      glovesFee: 40,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'sen-1', name: '1. Saha (Pasliga & VAR Kameralı)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
      { id: 'sen-2', name: '2. Saha (Isıtmalı Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '00:30-01:30', slotType: 'half' },
      { id: 'sen-3', name: '3. Saha (Hibrit Zemin)', surface: 'Hibrit Çim', startSlot: '09:00', lastSlot: '01:00-02:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-golbasi-mogan',
    city: 'Ankara',
    district: 'Gölbaşı',
    name: 'Gölbaşı Mogan Park Halı Saha',
    rating: 4.6,
    hourlyFee: 2700,
    subscriberFee: 2400,
    openingTime: '09:00',
    closingTime: '01:00',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 485 15 15',
    address: 'Mogan Gölü Kıyısı, Mogan Park Tesisleri, Gölbaşı, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 65,
      glovesRental: true,
      glovesFee: 35,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'mogan-1', name: 'Göl Manzaralı Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '00:00-01:00', slotType: 'full' },
      { id: 'mogan-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },

  // Mamak
  {
    id: 'ank-mamak-sehir-stadi',
    city: 'Ankara',
    district: 'Mamak',
    name: 'Mamak Şehir Stadı Halı Sahaları',
    rating: 4.4,
    hourlyFee: 2300,
    subscriberFee: 2000,
    openingTime: '08:30',
    closingTime: '23:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 368 22 11',
    address: 'Mamak Cad. No:15, Mamak, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 50,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'mam-1', name: '1. Saha', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: 'mam-2', name: '2. Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },
  {
    id: 'ank-basak-mamak',
    city: 'Ankara',
    district: 'Mamak',
    name: 'Başak Gençlik Spor Halı Saha Tesisleri',
    rating: 4.5,
    hourlyFee: 2500,
    subscriberFee: 2200,
    openingTime: '09:00',
    closingTime: '00:30',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 374 88 77',
    address: 'Başak Mah., 1680. Sok., Mamak, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'bsk-1', name: 'Açık Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '23:00-00:00', slotType: 'full' },
      { id: 'bsk-2', name: 'Kapalı Saha', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '23:30-00:30', slotType: 'half' },
    ],
  },

  // Altındağ
  {
    id: 'ank-19mayis-altindag',
    city: 'Ankara',
    district: 'Altındağ',
    name: '19 Mayıs Dış Sahalar Halı Saha Kompleksi',
    rating: 4.6,
    isPopular: true,
    hourlyFee: 2600,
    subscriberFee: 2300,
    openingTime: '08:00',
    closingTime: '23:30',
    optimalModes: ['7v7', '8v8'],
    tightModes: ['9v9'],
    phone: '0312 310 19 19',
    address: 'Ulus, 19 Mayıs Spor Kompleksi İçi, Altındağ, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 60,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: '19m-1', name: '1. Saha (Ana Zemin)', surface: 'Suni Çim', startSlot: '08:00', lastSlot: '22:00-23:00', slotType: 'full' },
      { id: '19m-2', name: '2. Saha', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:30-23:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-genclik-parki',
    city: 'Ankara',
    district: 'Altındağ',
    name: 'Gençlik Parkı Halı Saha Tesisleri',
    rating: 4.5,
    hourlyFee: 2500,
    subscriberFee: 2200,
    openingTime: '09:00',
    closingTime: '23:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 309 44 55',
    address: 'Gençlik Parkı İçi, Ulus, Altındağ, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 55,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'gp-1', name: 'Merkez Saha', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },

  // Sincan & Pursaklar
  {
    id: 'ank-sincan-fatih',
    city: 'Ankara',
    district: 'Sincan',
    name: 'Sincan Fatih Spor Kompleksi Halı Saha',
    rating: 4.4,
    hourlyFee: 2300,
    subscriberFee: 2050,
    openingTime: '09:00',
    closingTime: '00:00',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 270 33 44',
    address: 'Fatih Mah., Harikalar Diyarı Yanı, Sincan, Ankara',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 50,
      glovesRental: true,
      glovesFee: 25,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'snc-1', name: '1. Saha (Açık)', surface: 'Suni Çim', startSlot: '09:00', lastSlot: '23:00-00:00', slotType: 'full' },
      { id: 'snc-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:30', lastSlot: '22:30-23:30', slotType: 'half' },
    ],
  },
  {
    id: 'ank-pursaklar-tebessum',
    city: 'Ankara',
    district: 'Pursaklar',
    name: 'Pursaklar Tebessüm Halı Saha Tesisleri',
    rating: 4.5,
    hourlyFee: 2400,
    subscriberFee: 2100,
    openingTime: '08:30',
    closingTime: '23:30',
    optimalModes: ['7v7'],
    tightModes: ['8v8'],
    phone: '0312 527 10 20',
    address: 'Merkez Mah., Fatih Sultan Mehmet Cad., Pursaklar',
    equipmentRental: {
      bootsRental: true,
      bootsFee: 50,
      glovesRental: true,
      glovesFee: 30,
      vestsProvided: true,
      showerAvailable: true,
      parkingAvailable: true,
    },
    subFields: [
      { id: 'prs-1', name: '1. Saha (Açık)', surface: 'Suni Çim', startSlot: '08:30', lastSlot: '22:30-23:30', slotType: 'half' },
      { id: 'prs-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha', startSlot: '09:00', lastSlot: '22:00-23:00', slotType: 'full' },
    ],
  },

  // ─── İSTANBUL ──────────────────────────────────────────────────────────────

  {
    id: 'ist-macka',
    city: 'İstanbul',
    district: 'Beşiktaş',
    name: 'Maçka Spor Tesisleri',
    rating: 4.6,
    isPopular: true,
    subFields: [
      { id: 'mac-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'mac-2', name: '2. Saha', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'ist-galatasaray-adasi',
    city: 'İstanbul',
    district: 'Beşiktaş',
    name: 'Galatasaray Adası Spor Tesisleri',
    rating: 4.8,
    isPopular: true,
    subFields: [
      { id: 'gal-1', name: 'Kuzeybatı Sahası', surface: 'Suni Çim' },
      { id: 'gal-2', name: 'İç Kapalı Saha', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'ist-fenerbahce-kalamis',
    city: 'İstanbul',
    district: 'Kadıköy',
    name: 'Fenerbahçe Kalamış Spor Tesisleri',
    rating: 4.9,
    isPopular: true,
    subFields: [
      { id: 'fb-1', name: '1. Saha (Deniz Tarafı)', surface: 'Suni Çim' },
      { id: 'fb-2', name: '2. Saha', surface: 'Suni Çim' },
      { id: 'fb-3', name: 'Kapalı Salon', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'ist-uskudar-bel',
    city: 'İstanbul',
    district: 'Üsküdar',
    name: 'Üsküdar Belediyesi Spor Tesisleri',
    rating: 4.4,
    subFields: [
      { id: 'usk-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'usk-2', name: '2. Saha', surface: 'Suni Çim' },
    ],
  },
  {
    id: 'ist-maltepe-bel',
    city: 'İstanbul',
    district: 'Maltepe',
    name: 'Maltepe Sahil Halı Saha',
    rating: 4.5,
    subFields: [
      { id: 'malt-1', name: 'Ana Saha', surface: 'Suni Çim' },
    ],
  },
  {
    id: 'ist-pendik-bel',
    city: 'İstanbul',
    district: 'Pendik',
    name: 'Pendik Belediyesi Spor Tesisleri',
    rating: 4.3,
    subFields: [
      { id: 'pen-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'pen-2', name: '2. Kapalı Saha', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'ist-bagcilar-bel',
    city: 'İstanbul',
    district: 'Bağcılar',
    name: 'Bağcılar Belediyesi Olimpik Tesisleri',
    rating: 4.5,
    isPopular: true,
    subFields: [
      { id: 'bag-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'bag-2', name: '2. Saha', surface: 'Hibrit Çim' },
      { id: 'bag-3', name: 'Kapalı Saha', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'ist-sariyer-bel',
    city: 'İstanbul',
    district: 'Sarıyer',
    name: 'Sarıyer Belediyesi Halı Saha',
    rating: 4.4,
    subFields: [
      { id: 'sar-1', name: 'Ana Saha', surface: 'Suni Çim' },
      { id: 'sar-2', name: 'Arka Saha', surface: 'Suni Çim' },
    ],
  },
  {
    id: 'ist-sisli-bel',
    city: 'İstanbul',
    district: 'Şişli',
    name: 'Şişli Belediyesi Fulya Tesisleri',
    rating: 4.6,
    isPopular: true,
    subFields: [
      { id: 'sis-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'sis-2', name: '2. Saha (Kapalı)', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'ist-umraniye-bel',
    city: 'İstanbul',
    district: 'Ümraniye',
    name: 'Ümraniye Belediyesi Spor Tesisleri',
    rating: 4.4,
    subFields: [
      { id: 'umr-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'umr-2', name: '2. Saha', surface: 'Suni Çim' },
    ],
  },

  // ─── İZMİR ─────────────────────────────────────────────────────────────────

  {
    id: 'izm-karatas',
    city: 'İzmir',
    district: 'Konak',
    name: 'Karataş Halı Saha',
    rating: 4.4,
    subFields: [
      { id: 'karat-1', name: 'Tek Saha', surface: 'Suni Çim' },
    ],
  },
  {
    id: 'izm-bornova-ege',
    city: 'İzmir',
    district: 'Bornova',
    name: 'Ege Üniversitesi Spor Tesisleri',
    rating: 4.6,
    isPopular: true,
    subFields: [
      { id: 'ege-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'ege-2', name: '2. Saha', surface: 'Suni Çim' },
      { id: 'ege-3', name: 'Kapalı Saha', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'izm-karsiyaka-bel',
    city: 'İzmir',
    district: 'Karşıyaka',
    name: 'Karşıyaka Belediyesi Halı Saha',
    rating: 4.5,
    subFields: [
      { id: 'kar-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'kar-2', name: '2. Saha', surface: 'Kapalı Saha' },
    ],
  },
  {
    id: 'izm-alsancak-deu',
    city: 'İzmir',
    district: 'Konak',
    name: 'Dokuz Eylül Üniversitesi Halı Saha',
    rating: 4.3,
    subFields: [
      { id: 'deu-1', name: 'Ana Saha', surface: 'Suni Çim' },
    ],
  },
  {
    id: 'izm-bayrakli-bel',
    city: 'İzmir',
    district: 'Bayraklı',
    name: 'Bayraklı Belediyesi Spor Tesisleri',
    rating: 4.4,
    subFields: [
      { id: 'bay-1', name: '1. Saha', surface: 'Suni Çim' },
      { id: 'bay-2', name: '2. Saha', surface: 'Hibrit Çim' },
    ],
  },
];
